version: '3.8'

services:
 angular-postgres:
    image: postgres:15-alpine
    container_name: angular-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: angulartts-db
    ports:
      - "5433:5432"
    volumes:
      - angular_postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5


volumes:
  angular_postgres_data:
